<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <UseMicrosoftTestingPlatformRunner>false</UseMicrosoftTestingPlatformRunner>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="xunit.v3.mtp-v2" />
    <PackageReference Remove="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Remove="AwesomeAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Canton.Ledger.Kernel\Canton.Ledger.Kernel.csproj" />
  </ItemGroup>

</Project>
